### ISSUE TITLE
Walkthrough 

### ISSUE THREAD

**Issue by dtollaku** [k8-proxy/p1-stakeholder-requests#16]
The following GitHub wiki contains in-depth guides that cover the setup, management and testing of the ICAP project delivery. https://github.com/filetrust/icap-delivery/wiki
Azure Management Portal and ICAP Endpoint
 
The ICAP application has been deployed to a managed Kubernetes instance in Azure for your exclusive testing and usage. This has been done due to the delay in deployment of a Kubernetes cluster that conforms to the SOW (specifically SOW 2.2: Disconnected Installation).
·        ICAP Endpoint:
·        Management Portal:
o   No login is required. Pressing login without any details will sign in as a test user.
Access to the Azure environment has been provided (Further access can be provided upon request). Once the Kubernetes context is added to your machine, the open-source tools Octant and K9s can be used to view the internals of the cluster. See the ICAP Delivery Project wiki for details:
1.      How to configure your local machine for an Azure connection: https://github.com/filetrust/icap-delivery/wiki/Configuring-local-machine-for-Azure-connection
2.      How to setup Kubernetes CLI:
https://github.com/filetrust/icap-delivery/wiki/Kubernetes-CLI
3.      How to add the appropriate Kubernetes context to your machine: https://github.com/filetrust/icap-delivery/wiki/Set-Kubernetes-context-to-an-Azure-AKS-cluster
4.      How to setup and use Octant and K9s to view the internal of the cluster: https://github.com/filetrust/icap-delivery/wiki/Viewing-the-cluster-in-operation
5.      How to send request to the ICAP Endpoint:
https://github.com/filetrust/icap-delivery/wiki/Sending-files-via-C-ICAP-Client
 
Terraform Deployment to Azure Kubernetes Service
 
While you may be happy to use the endpoint that we have stood up, if you wish to deploy the early version of the application to your own Azure environment then we have provided Terraform code with full instructions on how to deploy the application. https://github.com/filetrust/icap-delivery/wiki/Deployment-of-ICAP-Application-to-AKS-cluster
 
Calling ICAP
To interact with the ICAP server we have provided two methods:
The first and simplest mechanism to send a file is to use the C-ICAP Client to send an individual file and receive a rebuild file in response. This is an open-source tool written in C. For ease of use we have pre-compiled it into a docker container. Full instructions on how to use this docker image can be found here: https://github.com/filetrust/icap-delivery/wiki/Sending-files-via-C-ICAP-Client
The second is an ICAP load test tool hosted in AWS that can generate the volume of requests required to validate SOW 3.1.2 Scalability Demonstration. The tool has an analytics dashboard that gives a visual representation of the requests sent to the target endpoint and a breakdown of their outcomes. https://github.com/filetrust/icap-delivery/wiki/Load-Test-Tool
These will soon be available as a public AMIs in AWS and we will update the wiki entry above when these become available.
Setting up the load test tool and becoming familiar with its operation will give the team a head start on validation at the point of delivery.
Ancillary Services (Proxy & Target Website)
Whilst this project is focussing on the delivery of an ICAP endpoint to Rebuild files, the end customer will be accessing via a configured device / appliance capable of interacting with an ICAP endpoint. To give an early representation of this a squid proxy fully configured to proxy an offline copy of the Glasswall Engineering website has also been virtualised into AMI and OVA formats. The squid proxy can be configured to interact with a running ICAP protocol (Any of the options provided above are candidates). Full details of how-to setup and use these will be provided here in due course: https://github.com/filetrust/icap-delivery/wiki/Proxy-Integration---Reference-Implementation

**Any ICAP endpoint can be used for this.**

**Comment by azopat** [comment]
i worked on the setup on azure. but i need to clarify few things on that ticket. The completion result is just to test that everything works on the test cluster i did or on another cluster ? Because in the link i see some sentence like “o No login is required. Pressing login without any details will sign in as a test user.” but i don’t know if there is another endpoint i should check. So basically i did the setup on an azure aks cluster and tested using this procedure https://github.com/filetrust/icap-delivery/wiki/Sending-files-via-C-ICAP-Client  and it works well. The load testing tool is not yet available as well as the reference integrations
