### ISSUE TITLE
Upload API and UI container images into Glasswall Dockerhub account.

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/p1-stakeholder-requests#18]
Upload API and UI container images into Glasswall Dockerhub account.

**Comment by NourEddineX** [comment]
As per @dtollaku , I should push to k8serviceaccount docker hub 
sow-rest-ui uploaded to https://hub.docker.com/r/k8serviceaccount/sow-rest-ui/tags can be pulled with `docker pull k8serviceaccount/sow-rest-ui`
sow-rest-api uploaded to https://hub.docker.com/r/k8serviceaccount/sow-rest-api/tags , can be pulled with `docker pull k8serviceaccount/sow-rest-api`

**Comment by yardenshoham** [comment]
@mahnouman is this acceptable or should I put it on `glasswall`?
