### ISSUE TITLE
Documented steps including any scripts used to list globally writable files in a cluster so it can be asserted that none of the files are associated to the application.

### ISSUE THREAD

**Issue by b24repo** [k8-proxy/p1-stakeholder-requests#3]
We have a requirement to assert that we create or make no use of globally-writable files as part of our application - given that our application is a Kubernetes cluster we need a method of showing that this is true. Being able to list the globally writable files in a container and excluding any that are part of the base OS would be a start. Being able to do this for all containers in a cluster in a few simple steps would be desired.

**Comment by gmuditdce** [comment]
PR raised for this issue - #6 

Please watch below videos and go through Readme on how we can fetch permissions of globally writable files from docker containers and k8 cluster pods

[HowToVideos.zip](https://github.com/k8-proxy/p1-stakeholder-requests/files/5291981/HowToVideos.zip)
