### ISSUE TITLE
Container image with the C-ICAP test client pre-made from the C codebase.

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/p1-stakeholder-requests#9]
Requirement:
Developers would find it useful to have a container image with the C-ICAP test client pre-made from the C codebase.
The test client is bundled in with the C-ICAP server components, which in turn are the foundation for Glasswall’s own C-ICAP server implementation.

https://github.com/filetrust/c-icap
Looking in this repository you will see that an example of building the code via a dockerfile exists – this is pretty much what we need (we don’t need the modules), but rather than the focus of the container being the server – the application we want access to is the `c-icap-client`, the code for which can be found in c-icap\c-icap\utils. If the build instructions are followed it is installed into the location /usr/local/c-icap/bin/c-icap-client by default. The arguments that should be provisioned are:
-i (icap_servername): The icap server name
-p (port): The server port
-s (service): The service name
-f (filename): Send this file to the icap server.
Default is to send an options request
-o filename: Save output to this file.

Developers should then be able to do a docker run (or docker compose run with config in a docker compose file) command which triggers the call to the c-icap-client and returns the stdout to the command line issuing the docker run. After running the command, the container should stop.

**Comment by MaNe2020** [comment]
@GINAGC maybe smth like this can help: https://github.com/k8-proxy/k8-performance-use-cases/tree/master/upword-devs/marija-neskovic/docker-c-icap
I worked on smth similar just someone should take a look on the codebase and see if this solution suits the need.

**Comment by svf97** [comment]
Hello all, Please check the following for reference:

- https://github.com/k8-proxy/k8-traffic-generator/blob/master/upwork-devs/faisal-adnan/JMeter/Dockerfile
- https://github.com/k8-proxy/k8-performance-use-cases/blob/master/upword-devs/marija-neskovic/docker-c-icap/Dockerfile

Note: We might want to check which base image is suitable for the requester as openjdk:8-jre may not be not secure enough.

**Comment by ab-tech-coder** [comment]
@GINAGC @svf97

**Comment by top-dev-mania** [comment]
I hope the below link will be useful to everyone.

[https://github.com/k8-proxy/p1-stakeholder-requests/tree/feature/test-icap-client](https://github.com/k8-proxy/p1-stakeholder-requests/tree/feature/test-icap-client
)
